### ISSUE TITLE
HTML and CSS on web site

### ISSUE THREAD

**Issue by djbpitt** [CarolineMcDonough/Sherlock-DH-Project#7]
The main page looks good, but there's some carelessness to the HTML and CSS that will make them difficult to maintain. Below are some details that should be addressed:

- XHTML doesn't use `<meta charset="UTF-8"/>` because the character set is specified instead in the XML declaration.
- CSS belongs in a separate CSS stylesheet, and not in a `<style>` element in the HTML.
- CSS belongs in a separate CSS stylesheet, and not on a `@style` attribute on an element.
- Don't use `!important` in the CSS. You don't need it.
- `<img>` elements require an `@alt` attribute
- No more than one `<h1>` on a page. 
- Don't separate paragraphs with `<br></br>` tags. Tag them as paragraphs.
- The left-side menu is a great place for an HTML list that is styled with Flexbox.
- Why use a `@class` on the `<footer>` instead of using the element name itself as the CSS selector?
- All the paragraphs except the one in the `<footer>` have the same two classes. Those can be one class, or, better, you can apply the styles to paragraphs (and different ones to `footer > p`).

**Comment by Sean-Shmulevich** [comment]
Changes have been made.
